# Day 3 assignment

# Question 1

In [1]:
import numpy as np
arr = np.arange(2,50,3)
print(arr)

[ 2  5  8 11 14 17 20 23 26 29 32 35 38 41 44 47]


# Question 2

In [5]:
lst1 = []
lst2 = []
for i in range(5):
    a = int(input())
    lst1.append(a)
print(lst1)
for i in range(5):
    b = int(input())
    lst2.append(b)
print(lst2)
c = np.array([lst1])
d = np.array([lst2])
print(np.sort(np.concatenate((c,d))))
    
    

1
4
2
7
5
[1, 4, 2, 7, 5]
3
6
8
9
10
[3, 6, 8, 9, 10]
[[ 1  2  4  5  7]
 [ 3  6  8  9 10]]


# Question 3

In [6]:
arr = np.array([[1,2,3],[8,4,12],[3,6,9]])
print(arr.ndim)
print(arr.size)

2
9


# Question 4

In [15]:
arr = np.array([1,4,2,6,3,8,7,5,9])
x = arr
x = x[np.newaxis]
print(x)
print(x.ndim)


[[1 4 2 6 3 8 7 5 9]]
2


# question 5

In [24]:
ar = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(np.vstack(ar))
print(np.hstack(ar))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[1 2 3 4 5 6 7 8 9]


# Question 6

In [25]:
a = np.array([1,3,1,5,3,7,5,8,1])
print(np.unique(a,return_counts=True))

(array([1, 3, 5, 7, 8]), array([3, 2, 2, 1, 1], dtype=int64))
